namespace Hafintech.API.Models
{
    public class Declaration
    {
        public string initType { get; set; }
        public int agencyId { get; set; }
        public int? businessId { get; set; }
        public int dclId { get; set; }
        public int createdAccId { get; set; }
        public int accountId { get; set; }
        public int type { get; set; }
        public int status { get; set; }
        public string statusCode { get; set; }
        public string dclNo { get; set; }
        public string firstDclNo { get; set; }
        public string branchNoDivDcl { get; set; }
        public string noDivisDivDcl { get; set; }
        public string tentativeDclNo { get; set; }
        public string dclKindCd { get; set; }
        public string cargoClsCd { get; set; }
        public string meansOfTrsCd { get; set; }
        public string clsOrg { get; set; }
        public string cstOffice { get; set; }
        public string cstSubSection { get; set; }
        public string timeLimReExp { get; set; }
        public string dclPlannedDate { get; set; }
        public string imperCd { get; set; }
        public string imperNm { get; set; }
        public string postcode { get; set; }
        public string addressOfImp { get; set; }
        public string phoneNoOfImp { get; set; }
        public string impCtrCd { get; set; }
        public string impCtrNm { get; set; }
        public string consignorCd { get; set; }
        public string consignorNm { get; set; }
        public string postcodeIdt { get; set; }
        public string address1Street { get; set; }
        public string address3CityNm { get; set; }
        public string countryNm { get; set; }
        public string countryCd { get; set; }
        public string exportCsgNm { get; set; }
        public string plannedDeclCd { get; set; }
        public Lscargono[] lsCargoNo { get; set; }
        public string cargoPiece { get; set; }
        public string pieceUnitCd { get; set; }
        public string cargoWeigGrs { get; set; }
        public string weigUnitCdGrs { get; set; }
        public string cstWrhCd { get; set; }
        public string marksAndNos { get; set; }
        public string loadVesselCd { get; set; }
        public string loadVesselAcNm { get; set; }
        public string arrDate { get; set; }
        public string unloadPortCd { get; set; }
        public string unloadPortNm { get; set; }
        public string loadLocCd { get; set; }
        public string loadLocNm { get; set; }
        public string noHandledCtn { get; set; }
        public string resultInsCd { get; set; }
        public Lsotherlawcode[] lsOtherLawCode { get; set; }
        public Lspermit[] lsPermit { get; set; }
        public string invClsCd { get; set; }
        public string eleInvRecNo { get; set; }
        public string invNo { get; set; }
        public string invDate { get; set; }
        public string termOfPay { get; set; }
        public string invPrcKindCd { get; set; }
        public string invPrcCdtCd { get; set; }
        public string invCurCd { get; set; }
        public string totalInvPrc { get; set; }
        public string valDemarCd { get; set; }
        public string compDclNo { get; set; }
        public string curCdBasePrc { get; set; }
        public string basePrcValAdj { get; set; }
        public string freightDemarCd { get; set; }
        public string freightCurCd { get; set; }
        public string freight { get; set; }
        public string insDemarCd { get; set; }
        public string insCurCd { get; set; }
        public string insAmt { get; set; }
        public string regNoIns { get; set; }
        public object[] lsAdjDemar { get; set; }
        public string evaluatedAmt { get; set; }
        public string totalDisEva { get; set; }
        public string detailsOfVal { get; set; }
        public string totalDisTaxVal { get; set; }
        public string taxPayer { get; set; }
        public string reasonCd { get; set; }
        public string bankPayCd { get; set; }
        public string bankPayIssYear { get; set; }
        public string bankPaySign { get; set; }
        public string bankPayNo { get; set; }
        public string extPayDueCd { get; set; }
        public string secSupplBankCd { get; set; }
        public string issuedYear { get; set; }
        public string secBankSign { get; set; }
        public string secNo { get; set; }
        public object[] clsAttachment { get; set; }
        public string attachmentNo { get; set; }
        public string permitWrhDate { get; set; }
        public string strDateTrs { get; set; }
        public Lstransinfo[] lsTransInfo { get; set; }
        public string arrDateTrnLoc { get; set; }
        public string strDateTrnLoc { get; set; }
        public string destinationTrs { get; set; }
        public string arrDateOfTrs { get; set; }
        public string notes { get; set; }
        public string etpControlNo { get; set; }
        public string cstInsCls { get; set; }
        public object[] lsCstIns { get; set; }
        public string caseTitCstIns { get; set; }
        public string contentCstIns { get; set; }
        public Listproduct[] listProducts { get; set; }

        public object clearanStatus { get; set; }

        public object declIdentity { get; set; }
        public object declFullname { get; set; }
        public object declMobile { get; set; }
        public object declAddress { get; set; }

        public object address2Street { get; set; }

        public object wtbWebsite { get; set; }
        public object wtbAddress { get; set; }
        public object wtbCountryCode { get; set; }

        public object clsCorReport { get; set; }
        public object insClsCd { get; set; }
        public object repTaxCd { get; set; }
        public object cstOfficeNm { get; set; }
        public object regDate { get; set; }
        public object regTime { get; set; }
        public object regDateOfCor { get; set; }
        public object regTimeOfCor { get; set; }
        public object timeLimReIE { get; set; }
        public object signTimeOver { get; set; }
        public object agentNm { get; set; }
        public object cstBrokerCd { get; set; }
        public object cstClrWrhNm { get; set; }
        public object totalTaxVal { get; set; }
        public object totalBPClsCd { get; set; }
        public object idtValType { get; set; }
        public object valClsCd { get; set; }
        public object formulaVal { get; set; }
        public object taxSubjectCd { get; set; }
        public object taxSubjectNm { get; set; }
        public object totalTaxAmt { get; set; }
        public object noColTotalTax { get; set; }
        public object totalPayTax { get; set; }
        public object secAmt { get; set; }
        public object curCd { get; set; }
        public object curExcRate { get; set; }
        public object paymentCls { get; set; }
        public object structure { get; set; }
        public object noOfDclColumn { get; set; }
        public object mngNoForUser { get; set; }
        public object dateOfPayDcl { get; set; }
        public object timeOfPayDcl { get; set; }
        public object title { get; set; }
        public object taxCdDefTax { get; set; }
        public object nameOfDefTax { get; set; }
        public object deadlinePayDef { get; set; }
        public object fieldNo { get; set; }
        public object prcReCfClsCd { get; set; }
        public object cstValSystem { get; set; }
        public object taxValCurCd { get; set; }
        public object taxValManual { get; set; }
        public object cstStdQtt { get; set; }
        public object msrUnitCdCst { get; set; }
        public object cstValUnitPrc { get; set; }
        public object unitCstUnitPrc { get; set; }
        public object impTaxRateCd { get; set; }
        public object impTaxRate { get; set; }
        public object impTaxRateInp { get; set; }
        public object impTaxAmt { get; set; }
        public object oriPlaceNm { get; set; }
        public object tarRdcImpTax { get; set; }
        public object itemNmOTax { get; set; }
        public object cstOTaxAmt { get; set; }
        public object stdOTax { get; set; }
        public object stdOTaxUnitCd { get; set; }
        public object taxRateOfOTax { get; set; }
        public object otherTaxAmt { get; set; }
        public object prvOTaxInLaw { get; set; }
        public string updatedDate { get; set; }
        public string createdDate { get; set; }
        public object contractNumber { get; set; }
        public object contractDate { get; set; }
        public object expiryDate { get; set; }
        public object agentCd { get; set; }
        public object coocReport { get; set; }
        public object rdcImpTaxAmt { get; set; }
        public object otaxCerAmt { get; set; }
        public object dateOfPermit { get; set; }
        public object timeOfPermit { get; set; }
        public object dateCmplInsp { get; set; }
        public object timeCmplInsp { get; set; }
        public object clsfOfPostInsp { get; set; }
        public object bpApprovalDate { get; set; }
        public object bpApprovalTime { get; set; }
        public object bpInspCmplDate { get; set; }
        public object bpInspCmplTime { get; set; }
        public object expNoDayPer { get; set; }
        public object dateImpDclCan { get; set; }
        public object timeImpDclCan { get; set; }
        public object dTrfManPrImDcl { get; set; }
        public object tTrfManPrImDcl { get; set; }
        public object dDataEleRegis { get; set; }
        public object tDataEleRegis { get; set; }
        public object pIDataEleRegis { get; set; }
        public object taxCodeGvat { get; set; }
        public object taxNameGvat { get; set; }
        public object dlnPmtGvat { get; set; }
        public object clsCrrReport { get; set; }
        public object houseAwbNo { get; set; }
        public object masterAwbNo { get; set; }
        public object flightNo { get; set; }
        public object itemName { get; set; }
        public object placeOriginCd { get; set; }
        public object cstValue { get; set; }
        public object eiControlNo { get; set; }
        public object sigAccId { get; set; }
        public object acceptAccId { get; set; }
        public object[] lsTaxInfo { get; set; }
        public object[] lsCurrency { get; set; }
        public Country[] Countrys { get; set; }
        public Currency[] Currencys { get; set; }
    }
    public class Attachment
    {
        public string clsAttachment { get; set; }
        public string attachmentNo { get; set; }
    }
    public class Lsotherlawcode
    {
        public string otherLawCd { get; set; }
    }

    public class Listproduct
    {
        public int productId { get; set; }
        public int accountId { get; set; }
        public int declarationId { get; set; }
        public string hSCd { get; set; }
        public string materialCd { get; set; }
        public string dutyRate { get; set; }
        public string absTariffRate { get; set; }
        public string absDutyUnitCd { get; set; }
        public string curCdAbsDuty { get; set; }
        public string itemName { get; set; }
        public string placeOriginCd { get; set; }
        public string importTaxClfCd { get; set; }
        public string tariffQuotaClf { get; set; }
        public string perUnitTaxCd { get; set; }
        public string qtt1 { get; set; }
        public string qttUnitCd1 { get; set; }
        public string qtt2 { get; set; }
        public string qttUnitCd2 { get; set; }
        public string invValue { get; set; }
        public string invUnitPrice { get; set; }
        public string unitPriceCurCd { get; set; }
        public string priceQttUnit { get; set; }
        public string cstValueCurCd { get; set; }
        public string cstValue { get; set; }
        public object[] lsValuationNo { get; set; }
        public string tenDclLineNo { get; set; }
        public string taxExpLsNo { get; set; }
        public string taxExpLsLineNo { get; set; }
        public string rdcImpTaxCd { get; set; }
        public string rdcAmtImpTax { get; set; }
        public Lsothertax[] lsOtherTax { get; set; }
    }

    public class Lsothertax
    {
        public string oTaxTypeCd { get; set; }
        public string oTaxRdcCd { get; set; }
        public string oTaxRdcAmt { get; set; }
    }
}